### ISSUE TITLE
Is it possible to remove specific modes in atmospher layer using HCIPy?

### ISSUE THREAD

**Issue by Oswald522** [ehpor/hcipy#194]
I am currently simulating adaptive optics systems using HCIPy and I am wondering if there are any methods available to remove specific modes in the atmospheric layer constructed using the layer module. Specifically, I would like to remove the zernike modes up to the second order.

Thank you for your assistance.

**Comment by ehpor** [comment]
@Oswald522 Yes, that should work as you expect it to. Make sure you're removing the right modes. Ten modes is more than second order Zernikes.

And yes, that's an oversight in the code: I've always used something like:
```python
for t in np.arange(0, num_iterations) * dt:
    atmosphere.evolve_until(t)

    # Do stuff.
```

so the `evolve_until()` call always goes before getting the phase for that layer, so I've never run into this bug. BTW, instead of `evolve_until(0.1)`, an `evolve_until(0)` also works, but is not required if you set up your loop the way I did. I'll work on fixing this bug at some point (I don't have time right now to do so, but I'll try to find some during next month).

**Comment by Oswald522** [comment]
Thank you very much for your help, I will close this issue.
