### ISSUE TITLE
probable issue with Shack hartmann wavefront sensor?

### ISSUE THREAD

**Issue by AyanS13** [ehpor/hcipy#242]
https://github.com/ehpor/hcipy/blob/29118823140494935c688fc58104b0b6437e143f/hcipy/wavefront_sensing/shack_hartmann.py#L20

I have a few queries regarding this part of the code.

1) The array x is defined as (pupil_diameter, pupil_diameter) with a step size of lenslet_diameter. But shouldn't it be (-radius, radius) as the centre is at 0? 

2) In the self.mla_grid command, do the grid points represent the corners of the lenslets or the centres ? 

Thanks a lot!!

**Comment by ehpor** [comment]
Hi Ayan. Thanks for the questions.

1. Indeed this is a very clunky way to set this up. The purpose of doing `pupil_diameter` instead of `pupil_diameter/2` is to avoid edge effects. Having the MLA extend beyond the pupil edge helps avoiding diffraction effects. In practice, the MLA is larger than the pupil. Why not just one extra microlens? No clue: doubling the number of microlenses is a quick and easy choice. 
  A bigger problem imo is that the resulting MLA is not symmetric, as they usually are in actual AO systems. The `mla_grid` should probably be a `make_uniform_grid()` call with appropriate extent and shape.
2. The grid points represent the center of each microlenses.

**Comment by AyanS13** [comment]
Thanks a lot for the info. 

Actually, I am trying to create a lenslet array that would almost cover a 6x6 lenslet array. That is how our lab experiment has been setup. Can you suggest something to create something like the image that I have attached below (the dots are the centres of the lenslets that are used to create a grid for the lenslet array)? 

![WhatsApp Image 2024-11-14 at 15 20 36](https://github.com/user-attachments/assets/1c496bdf-f1d5-47b0-894f-8fc05ef1e785)

**Comment by AyanS13** [comment]
Thanks a lot!!
I was finally able to make it work.
