### ISSUE TITLE
Clarity on Atmosphere Adaptive Optics Example

### ISSUE THREAD

**Issue by rahulbhadani** [ehpor/hcipy#39]
Hi,
       I am following example: https://github.com/ehpor/hcipy/blob/master/doc/getting_started/3_atmosphere_adaptive_optics.ipynb

I have the following confusion:
1. `focal_grid = make_focal_grid(pupil_grid, 8, 16, wavelength=wavelength)`
Is `16` the focal length of the converging lens and `8` number of the airy disk?

2. When creating Cn2Square, why the wavelength used is different from the one specified earlier? Won't it create some sort of inconsistency? How will the use of different wavelength for creating atmospheric turbulence be justified than one used to create focal_grid?

Thanks.

**Comment by ehpor** [comment]
1. This uses the old function signature `make_focal_grid(pupil_grid, q, num_airy, focal_length, ...)`, which is deprecated now. This signature should not be used in new code, but wasn't changed in the getting-started guide yet. In this signature, 8 is the number of pixels per lam/D (`q`) and 16 is the radius of the fov in lam/D (`num_airy`). Pupil diameter is taken to be the extent of `pupil_grid`.
2. For calculating the Cn squared, the Fried parameter is always defined at a certain wavelength, often 500nm. This is the wavelength which should be passed to `Cn_squared_from_fried_parameter()`. When propagating light at other wavelengths, the scaling factor will automatically be taken into account correctly (so that longer wavelengths will have a longer Fried parameter, etc...). Cn squared is assumed to be constant with wavelength, while Fried parameter isn't.

**Comment by rahulbhadani** [comment]
Okay, thanks for your reply. I am still confused about the point no. 1.

I am working on a fork of wfs_examples. It seems but it seems that branch is not updated as you are saying signature for `make_focal_grid` is changed. 

Anyways: this is what I am trying to achieve right now:

1. Create a flat wavefront.
2. Pass through atmospheric turbulence.
3. Receive on a deformable mirror, and do wavefront sensing using a Wavefront sensor. 
4. Depending upon the sensed wavefront, change the amplitude of different actuators to correct the wavefront in the loop. 

I have got an example in wfs_example branch but as some function signature are not clear but I am not even sure if what I am doing is correct or not.

**Comment by rahulbhadani** [comment]
@ehpor @VikramRadhakrishnan ,  I worked on an example AO based on already provided examples. Unfortunately, AO doesn't seem to do anything as can be seen https://github.com/rahulbhadani/hcipy/blob/rahul_master_ao/ao_examples/AO_EXAMPLE_2.ipynb

I also have made some comments in CAPSLOCK where I found some confusion and need further clarification. Can you please go through and help me on this? 

Thanks.
Rahul

**Comment by ehpor** [comment]
I'm going to close this, as this is handled via email now.
