### ISSUE TITLE
Standard asphere surface profiles

### ISSUE THREAD

**Issue by syhaffert** [ehpor/hcipy#45]
I am currently working on the finishing touch of my aspheric microlens arrays. This will be pushed later this week. For this I needed to define an aspheric surface. I have now followed the definition of Zemax for an EvenAsphereSurface. But there are many other types of surface profiles such as the uneven asphere, even + uneven asphere, surfaces that only change in x or y. 

Does it make sense to make a separate file in the optics folder where all these standard surface shapes are defined?

**Comment by syhaffert** [comment]
Maybe as a similar issue, how will we handle standard refractive index profiles? Do we make a separate glass.py file?

**Comment by ehpor** [comment]
Yes, I think it's a good idea to have a small library of these aspheric, conic and spherical surface sags. I'd keep it brief though. To make them useful outside of micro-optics would probably need more advanced optical propagation methods, which are not implemented now. Any more than the following?

- Even aspheric
- Even-odd aspheric
- Conic
- Spherical

For refractive indices. A wrapper to an existing library would be preferable for me, but I haven't seen any good ones. PyTMM looks okay, but that is not pip installable as far as I can see, and including it outright into HCIPy or a derivative is not possible due to their license. Maybe a few formulas for the most common glasses (BK7, SF11, ...) and a few general implementations (Sellmeier, ...), with coefficients as arguments? Into glass.py would be my choice as well.

**Comment by syhaffert** [comment]
I think those surfaces are fine. I will add them in my current working branch in a separate surface file.

For the refractive index I think we may be able to use: https://github.com/HugoGuillen/refractiveindex.info-sqlite

This one has no license and has a relatively simple interface. It also allows you to look for materials within certain ranges of refractive indices.

**Comment by ehpor** [comment]
That one is also not pip-installable, and is also based on PyTMM, and as such, must also necessarily be GPL licensed. If you look in the code, a large part is copy-pasted with small modifications. You can not re-release a GPL code as non-licensed code or MIT licensed, even if you modify it. While officially, we wouldn't be directly breaking the license, we would do it indirectly.

**Comment by syhaffert** [comment]
Well then it would be easiest to include several glasses by hand. I have already implemented a couple of Cauchy and Sellmeier equations.

**Comment by syhaffert** [comment]
I have added the two standard glass catalogues from Schott and Ohara in my branch (fiber_LP_modes). Those were freely available from the website of Schott and Ohara. How should we order such files? Currently I just put them in the optics folder, like the xinetics influence functions. Should we add some Data folder at some point for these types of files?

**Comment by syhaffert** [comment]
This has now been resolved in the new LP_fiber_modes branch, therefore I will close this issue.
