### ISSUE TITLE
Backward propagation on FraunhoferPropagator fails

### ISSUE THREAD

**Issue by ehpor** [ehpor/hcipy#55]
Minimal reproducing code:
```python
from hcipy import *

pupil_grid = make_pupil_grid(512, 1)
focal_grid = make_focal_grid(4, 16)
prop = FraunhoferPropagator(pupil_grid, focal_grid)

wf = Wavefront(circular_aperture(1)(focal_grid))
pup = prop.backward(wf)
```

Traceback:
```
Traceback (most recent call last):
  File ".\test.py", line 8, in <module>
    pup = prop.backward(wf)
  File "c:\users\emiel por\github\hcipy\hcipy\optics\optical_element.py", line 760, in res
    instance_data = self.get_instance_data(None, wavefront.grid, wavefront.wavelength)
  File "c:\users\emiel por\github\hcipy\hcipy\optics\optical_element.py", line 632, in get_instance_data
    self.make_instance(instance_data, input_grid, output_grid, wavelength)
  File "c:\users\emiel por\github\hcipy\hcipy\propagation\fraunhofer.py", line 38, in make_instance     
    instance_data.fourier_transform = make_fourier_transform(input_grid, instance_data.uv_grid)
  File "c:\users\emiel por\github\hcipy\hcipy\fourier\fourier_transform.py", line 162, in make_fourier_transform
    if input_grid.is_separated and input_grid.is_('cartesian') and output_grid.is_separated and output_grid.is_('cartesian') and input_grid.ndim in [1,2]:
AttributeError: 'function' object has no attribute 'is_separated'
```
Reported by @chen-pin

**Comment by ehpor** [comment]
@chen-pin The PR should have fixed the issue. Can you let me know if this is the case for you as well? You can install the fixed version from Github, see [the installation page](https://docs.hcipy.org/0.3.0/installation.html) on how to do this.

**Comment by chen-pin** [comment]
Hi Emiel,
Thank you very much for working on resolving this so quickly!  I did the following to install the update:>   git clone https://github.com/ehpor/hcipy
>  cd hcipy>  pip install -e ~/anaconda3/lib/python3.7/site-packages/hcipy
And I get the following error:"File "setup.py" not found. Directory cannot be installed in editable mode: /home/pinchen/anaconda3/lib/python3.7/site-packages/hcipy"
What am I doing wrong?
Best,Pin

    On Thursday, January 23, 2020, 9:29:23 AM PST, Emiel H. Por <notifications@github.com> wrote:  
 
 
@chen-pin The PR should have fixed the issue. Can you let me know if this is the case for you as well? You can install the fixed version from Github, see the installation page on how to do this.


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
ehpor/hcipy

A framework for performing optical propagation simulations, meant for high contrast imaging, in Python. - ehpor/...
 |

 |

 |

> 


.

**Comment by ehpor** [comment]
If you had a PyPI installation before, you first need to uninstall that:
```shell
pip uninstall hcipy
```
then reinstall from source:
```shell
git clone https://github.com/ehpor/hcipy
cd hcipy
pip install -e .
```
You need to have the period at the end (ie. install from the current directory, that is, the one you just cloned into).

**Comment by chen-pin** [comment]
Hi Emiel,
I am happy to report that I successfully updated HCIPy per your instructions, and my code now works.  The bug is fixed!
Thank you again for all the help and support!
Best,Pin

    On Thursday, January 23, 2020, 3:20:40 PM PST, Emiel H. Por <notifications@github.com> wrote:  
 
 
If you had a PyPI installation before, you first need to uninstall that:
pip uninstall hcipy
then reinstall from source:
git clone https://github.com/ehpor/hcipy
cd hcipy
pip install -e .
You need to have the period at the end (ie. install from the current directory, that is, the one you just cloned into).

**Comment by chen-pin** [comment]
Hi Emiel,
Is there a way to pip install a version that includes the above-referenced bug fix?  I would like to share my code with a co-worker, and it would be helpful if I can tell him to simply do something like <pip install hcipy --upgrade> to make my code run w/o error.    

Thank you!Pin

    On Thursday, January 23, 2020, 5:47:51 PM PST, Pin Chen <pin_chen2000@yahoo.com> wrote:  
 
  Hi Emiel,
I am happy to report that I successfully updated HCIPy per your instructions, and my code now works.  The bug is fixed!
Thank you again for all the help and support!
Best,Pin

    On Thursday, January 23, 2020, 3:20:40 PM PST, Emiel H. Por <notifications@github.com> wrote:  
 
 
If you had a PyPI installation before, you first need to uninstall that:
pip uninstall hcipy
then reinstall from source:
git clone https://github.com/ehpor/hcipy
cd hcipy
pip install -e .
You need to have the period at the end (ie. install from the current directory, that is, the one you just cloned into).

**Comment by ehpor** [comment]
I was planning to do a bugfix update on pip after about a month of the 0.3.0 release so that most of the bugs were found and fixed. I guess time got away from me. I'll try to get the 0.3.1 version out today (maybe tomorrow).

**Comment by ehpor** [comment]
HCIPy 0.3.1 should be available on pip now.

**Comment by chen-pin** [comment]
Hi Emiel,
A belated thank you, I installed v0.3.1 right away, and it works great.  -Pin

    On Thursday, April 2, 2020, 3:17:02 AM PDT, Emiel H. Por <notifications@github.com> wrote:  
 
 


HCIPy 0.3.1 should be available on pip now.

**Comment by chen-pin** [comment]
Hi Emiel,
I hope this message finds you well!  I am trying to run parallel coronagraph simulations using HCIPy and the <multiprocessing> module.  I am encountering a problem that appears to be a pickling problem; <multiprocessing> uses <pickle> to pass information among processes.  Apparently, `grid` information is lost when pickle serializes an `OpticalElement`.  Any advice/help would be much appreciated.  Here is the full trace-back:---
Traceback (most recent call last):
  File "sleec_run.py", line 120, in <module>
    run_emcee()
  File "sleec_run.py", line 116, in run_emcee
    sampler.run_mcmc(ini_positns, input_pars['nsteps'], progress=True)
  File "/home/pinchen/anaconda3/envs/dev/lib/python3.8/site-packages/emcee/ensemble.py", line 384, in run_mcmc
    for results in self.sample(initial_state, iterations=nsteps, **kwargs):
  File "/home/pinchen/anaconda3/envs/dev/lib/python3.8/site-packages/emcee/ensemble.py", line 285, in sample
    state.log_prob, state.blobs = self.compute_log_prob(state.coords)
  File "/home/pinchen/anaconda3/envs/dev/lib/python3.8/site-packages/emcee/ensemble.py", line 427, in compute_log_prob
    map_func(self.log_prob_fn, (p[i] for i in range(len(p))))
  File "/home/pinchen/anaconda3/envs/dev/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/pinchen/anaconda3/envs/dev/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/home/pinchen/anaconda3/envs/dev/lib/python3.8/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/home/pinchen/anaconda3/envs/dev/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/pinchen/anaconda3/envs/dev/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/pinchen/anaconda3/envs/dev/lib/python3.8/site-packages/hcipy/optics/optical_element.py", line 713, in attribute
    instance_data = self.get_instance_data(input_grid, output_grid, wavelength)
  File "/home/pinchen/anaconda3/envs/dev/lib/python3.8/site-packages/hcipy/optics/optical_element.py", line 607, in get_instance_data
    cache_keys = self._get_cache_keys(input_grid, output_grid, wavelength)
  File "/home/pinchen/anaconda3/envs/dev/lib/python3.8/site-packages/hcipy/optics/optical_element.py", line 319, in _get_cache_keys
    raise ValueError('Grid dependent, but no grids are given for lookup.')
ValueError: Grid dependent, but no grids are given for lookup.
---
If you would like me to submit this issue on Github, please let me know.  

Thank you very much in advance!
Pin

    On Thursday, April 2, 2020, 3:17:02 AM PDT, Emiel H. Por <notifications@github.com> wrote:  
 
 


HCIPy 0.3.1 should be available on pip now.

**Comment by ehpor** [comment]
I opened up an issue for this, see #69. BTW, you are aware that by replying to these emails, you are posting on Github, right? So everyone can see these messages; it's not private. They are under `https://github.com/ehpor/hcipy/issues/55`.
