### ISSUE TITLE
Wavefront creation fails on Magellan aperture...

### ISSUE THREAD

**Issue by mfeldt** [ehpor/hcipy#74]
```
>>> from hcipy import *
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> pupil_grid = make_pupil_grid(1024)
>>> aperture = make_magellan_aperture(True)
>>> wavefront = Wavefront(aperture, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/feldt/Python/HCIPY/venv/lib/python3.6/site-packages/hcipy/optics/wavefront.py", line 58, in __init__
    self._electric_field = electric_field.astype('complex')
AttributeError: 'function' object has no attribute 'astype'

```

I guess it's due to the wavefront object in wavefront.py containing both a variable and a property/function of the name "electric_field".

Curiously, it works on a circular aperture.

Python version is 3.6

**Comment by ehpor** [comment]
The `make_magellan_aperture(True)` statement returns a Field generator. (The `True` indicates that the pupil should be rescaled so that its diameter is 1 and not 6.5 meter.) This Field generator should be evaluated on a Grid to get a Field, which can then be passed into the Wavefront initializer.

For me, a circular aperture works in the same way:
```python
aperture = circular_aperture(1)
wavefront = Wavefront(aperture, 1)
```
raises an Exception
```
AttributeError: 'function' object has no attribute 'astype'
```
while
```python
aperture = circular_aperture(1)(pupil_grid)
wavefront = Wavefront(aperture, 1)
```
works as expected.

So for your example:
```python
aperture = make_magellan_aperture(True)(pupil_grid)
wavefront = Wavefront(aperture, 1)
```

**Comment by mfeldt** [comment]
OKI, I see.  Thx for the quick response.
